language: ruby
rvm:
  - 2.1.1
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - psql -c "create user rails_gallery with password 'SecretPassword';" -U postgres
  - psql -c "create database rails_gallery_test;" -U postgres
  - psql -c "grant all privileges on rails_gallery_test to rails_gallery;" -U postgres
install:
  - bundle install