language: ruby
rvm:
  - 2.1.1
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "create database rails_gallery_test;" -U postgres
install:
  - bundle install